### ISSUE TITLE
Allow notification attachments

### ISSUE THREAD

**Issue by reluem** [codefog/contao-events_subscriptions#10]
Hi, 

is there a way to allow for notification attachments with simple tokens?
Every token I enter into the field (be it ##event_*##, ##recipient_email## or any other listed in the documentation) is shown as invalid.

Thank you!

Contao 4.6.13, latest version of events_subscriptions

**Comment by qzminski** [comment]
Hey @reluem, I don't think there is any token that would be suitable for that as it must provide the file path. What's the exact use case for you?

**Comment by reluem** [comment]
Hi, 

I am generating an .ics with the onSubscribe Hook. This .ics is then saved as event_alias.ics.

If I could use for instance the event_enclosure token in the notification, I could attach the file to the email sent.

Is this even possible? I am not sure if the hook is even run in parallel or before the actual message is sent. Thus I don’t know (yet) if my file is even accessible with the token.

Does this make sense, or did you have a similar problem in the past?

Thanks!

**Comment by qzminski** [comment]
First of all you would have to extend the available tokens for this notification type like so:

```php
// config.php
$GLOBALS['NOTIFICATION_CENTER']['NOTIFICATION_TYPE']['events_subscriptions']['events_subscriptions_subscribe']['attachment_tokens'] = ['my_token'];
```

That makes sure your token is treated as valid. Then the easiest way to provide a value for that token would be to override the subscription class [like stated in the developer documentation](https://github.com/codefog/contao-events_subscriptions/blob/master/docs/08-developers.md#subscription-types) and provide the token value in this method:

https://github.com/codefog/contao-events_subscriptions/blob/master/src/Codefog/EventsSubscriptions/Subscription/GuestSubscription.php#L161-L172

**Comment by reluem** [comment]
Works like a charm. 
I extended the guestSubscription Class and added my 'ics_file' token with the path as value. This is then used in the notification.

Thanks for your help!
