### ISSUE TITLE
Bug? in tl_calendar_events_subscription.php regarding deleteConfirm

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-events_subscriptions#102]
https://github.com/codefog/contao-events_subscriptions/blob/5cadb72527f0ef846bdde352a79d583398baa700/dca/tl_calendar_events_subscription.php#L86
```
(\''.$GLOBALS[
('\'.$GLOBALS[
```

**Comment by qzminski** [comment]
Why do you think it's a bug?

**Comment by Aybee** [comment]
Trying to solve this
https://github.com/contao/contao/issues/5846

```
While doing a migrate on the console I get this warning
[xxx:~/xxx/vendor/bin] 255 $ php contao-console contao:migrate -v
PHP Warning:  Undefined array key "deleteConfirm" in /xxx/vendor/codefog/contao-events_subscriptions/dca/tl_calendar_events_subscription.php on line 86
```

**Comment by qzminski** [comment]
I have just released 2.16.4, that should fix your problem.

**Comment by Kahmoon** [comment]
https://github.com/codefog/contao-events_subscriptions/issues/91

This Bug also fixed in 2.16.4?

**Comment by qzminski** [comment]
No, I haven't find time to fix it yet.

**Comment by Aybee** [comment]
Maybe it's no bug, don't know.
