### ISSUE TITLE
Using special characters in subject

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#13]
Hi,

im using the variable ##event_title## in subject and body of notification center. Some special characters get "destroyed" in mailsubject. Quotationmarks for example are no problem. Brakets are a problem in subject not in body.

`Anmeldung für Event: Jagdpraxis - Wildbrethygiene (Teil 1) am 01.07.2019`
becomes
`Anmeldung für Event: Jagdpraxis - Wildbrethygiene &#40;Teil 1&#41; am 01.07.2019`

Is this problem related to contao-event_subscriptions or notification center?

Frank

**Comment by qzminski** [comment]
@aschempp @Toflar what do you think about this? Have you encountered a similar problem?

The tokens are formatted by `Haste\Util\Format::dcaValue()` and this is clearly a problem if the DCA field has no `decodeEntities=>true`. I don't think we can just decode all the tokens as it could potentially break the HTML due to `&lt;` or `&gt;` being decoded… 

Maybe we should only decode entities for e-mail subjects:

https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/MessageDraft/EmailMessageDraft.php#L132

… using the `NO_ENTITIES` flag:

https://github.com/codefog/contao-haste/blob/master/library/Haste/Util/StringUtil.php#L98

**Comment by Toflar** [comment]
It should be decoded where you want it to be decoded. If you think about if Contao did it correctly we would not have encoded values and thus think about where to encode it too. So it depends where it‘s going to be used.

**Comment by Toflar** [comment]
I think the ones parsing the tokens should decide. For NC for example, it knows it wants decoded html entities in the subject. But probably not in the body if the message is of type html.

**Comment by qzminski** [comment]
Well, since we already hardcode the `NO_TAGS` and `NO_BREAKS` flags for the e-mail subject I think we could also hardcode `NO_ENTITIES`. I can't see a reason why entities would ever be encoded there.

**Comment by Toflar** [comment]
Yes, in case of subject that's correct. But HTML body is different imho.

**Comment by qzminski** [comment]
Sure and that's why I would add the `NO_ENTITIES` flag here in order to solve this problem: https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/MessageDraft/EmailMessageDraft.php#L132

Sounds good?

**Comment by Toflar** [comment]
That's good, yes but it should be addressed in the body as well, is what I'm trying to say.

**Comment by qzminski** [comment]
For the HTML body we shouldn't change anything as it's the token parser/generator that decides whether each token has entities encoded or not.

For the text body however, we could go with `NO_ENTITIES` flag as well. One drawback I can imagine is that some e-mail clients my complain or try to interpret that the e-mail body has been provided as plain text but contains some HTML tags. Thus maybe it would be better not to touch it yet… until someone reports a bug 😅

**Comment by qzminski** [comment]
@Kahmoon can you check if https://github.com/terminal42/contao-notification_center/commit/f933596e6ad515e8a7e5e3f47ef298deead2a67b solves the problem for you?

**Comment by Kahmoon** [comment]
Yep! Looks good

**Comment by qzminski** [comment]
@Kahmoon please update the notification_center to 1.5.3 and that should solve the problem :+1:
