### ISSUE TITLE
Member Groups on subscription rights

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#14]
Is a feature request an issue? Sorry if i am wrong here.

Actually there are only two options to restrict registrations (guest, user). We use a pretty big right system for our courses. Just "user" is not enough in some cases. Some event archives are visible for more then one course but some events should be joinable just for explicit groups.

In the old module simple-event-registration we could choose every contao member group like any content element.

Is it possible to choose all existing member groups like other content elements?

VG Frank

**Comment by qzminski** [comment]
You can limit the calendars or events to certain member groups but that will mean that members outside of those groups won't be able to even see those entries. If you need those users to see the events but limit the subscription itself to certain member groups, that would be a new feature request.

**Comment by Kahmoon** [comment]
Yes, but our member groups grow pretty fast. So common event archives must be edited every time when a new group is created. For me thats ok....customer isn´t that smart...i can hear my phone ringing yet :)

Actually there are archives allowed group "students". Every student has this group. Plus he has a group course number. For every course number there is an own event archive.

Some events (e.g. exams) are an event for a common archive but should be subscribeable only for course x + y. I cannot put them into a course archive because then i have to create two events (archive couse x + archive course y). I also cannot remove the other groups from the common archive because then they cannot see the other events.

I hope this explanation makes sense :-)

Frank

**Comment by qzminski** [comment]
Not sure if I get it correctly… if we introduce the member group restriction on calendar/archive level, would that solve your problem? That would mean you can restrict subscription of calendar A events to member group A, and calendar B events to member group B.

… or the other way around – in member group settings, set which calendar can members subscribe to?

**Comment by Kahmoon** [comment]
Correct. You have to restrict the subscription in an event itself...ot the whole archive. The basic functionallity is already there (guest, user) an overwrite default settings in calendar archive.

So its possibe that group A, B, C see events in calendar "public". But only members of group A and group B can subscribe to an event.

**Comment by Kahmoon** [comment]
Theoretically "guest, user" functionality does not have to be replaced. Maybe an additional checkbox "advanced" in Contao or Event settings would be an option.

So the options from 

- guest
- user

becomes

- guest
- user
- Membergroup 1
- Membergroup 2
- Membergroup 3
- ....

VG Frank

**Comment by qzminski** [comment]
That's an interesting feature but right now I have no resources to implement it. If it is very urgent you can contact me privately at info@codefog.pl and we'll see what can be done.

**Comment by Kahmoon** [comment]
Oh :-(. OK

**Comment by Kahmoon** [comment]
I wrote you an email regarding a paid order for this feature.

VG Frank

**Comment by qzminski** [comment]
Implemented in ce07e80.

**Comment by Kahmoon** [comment]
Hey Kamil,

I have a question. Due to our advanced subscription system we can choose which member groups are allowed to subscribe. Super nice! But sometimes other groups can see this event but not subscribe and they don´t understand why. How can I show this data of allowed member groups in the event detail/subscription form. Is there a variable I didn´t see in the documentation?

Frank
