### ISSUE TITLE
Add own form fields on an easy way

### ISSUE THREAD

**Issue by jankout** [codefog/contao-events_subscriptions#15]
Hello Kamil, 

I would like to ask you whether you could implement a hook/function to allow to add own form fields on an easy way than it's possible now. 

I would like to use your extension for booking of tickets and I need a few of another fields (e.g. number, discount). 

Thank you. Best wishes, Jan

P.S.: I hope my issue is okay. Unfortunately I couldn't find any easy way to do it. That's why I'm asking you here.

**Comment by qzminski** [comment]
Adding new fields requires some experience in developing for Contao and there is no way to provide any simple hook for that. Please refer to the [developer documentation](https://github.com/codefog/contao-events_subscriptions/blob/master/docs/08-developers.md).

In first place you have to add new fields to the `tl_calendar_events_subscription` table and then override (or create a new one) subscription type.

**Comment by jankout** [comment]
Ok. Yesterday I posted my question in the forum. I know the way how to add custom fields to Contao modules like news, events etc. I’m just not sure with your extension. 

Could look at my forum post and let me know what I did wrong, please? 

https://community.contao.org/de/showthread.php?73749-contao-events_subscriptions-Formular-um-eigene-Felder-erweitern

Thanks. J.
