### ISSUE TITLE
Number field 'Participants' per registration

### ISSUE THREAD

**Issue by DanEi75** [codefog/contao-events_subscriptions#16]
Great extension. I 'miss' only one thing: A person could register for an event but also give the number of participants (for example for children). So, a number field 'Participants' per registration would be great, which is also considered for the calculation for the total number of participants.

**Comment by DanEi75** [comment]
Hi  @qzminski 

Thank you very much for your answer. Well, this seems to be too complicated for me. But of course, I'd love to see this ehancement in the core.

Do you have time to implement this as a paid job? No problem if it becomes part of the core, but I think that's an useful enhancement for everybody - and yes, I need it until end of February ;-).

**Comment by qzminski** [comment]
Hey @DanEi75 please drop me a line at info@codefog.pl and we'll see what can be done.

**Comment by Aybee** [comment]
> ... the number of participants (for example for children). ...

Yes, or your partner or friend/s. My customer also needs this.

**Comment by qzminski** [comment]
Released in 2.9.0.
