### ISSUE TITLE
event_subscription - add a new subscription in backend

### ISSUE THREAD

**Issue by b-fender** [codefog/contao-events_subscriptions#2]
Hi!
Thanks for your event_subscriptions module!
Are you still developing this projekt?
I found the following error in Your Module: (Contao 3.5.24)

In the Contao Backend go to events
choose an event list
click on the right side on the subscriptions button of an event
click on "new subscription"

Now you got this error message in Contao error.log:
(I tested it in two different server environments, debian php 5.6)

[09-Mar-2017 14:56:20 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Column 'addedBy' cannot be null (INSERT INTO tl_calendar_events_subscriptions (addedBy, pid, tstamp) VALUES (NULL, '9', 0))' thrown in /home/www/xxx/html/website/system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /home/www/xxx/html/website/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /home/www/xxx/html/website/system/modules/core/drivers/DC_Table.php(689): Contao\Database\Statement->execute()
#2 /home/www/xxx/html/website/system/modules/core/classes/Backend.php(650): Contao\DC_Table->create()
#3 /home/www/xxx/html/website/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#4 /home/www/xxx/html/website/contao/main.php(20): Contao\BackendMain->run()
#5 {main}
[09-Mar-2017 14:57:15 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Column 'addedBy' cannot be null (INSERT INTO tl_calendar_events_subscriptions (addedBy, pid, tstamp) VALUES (NULL, '9', 0))' thrown in /home/www/xxx/html/website/system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /home/www/xxx/html/website/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /home/www/xxx/html/website/system/modules/core/drivers/DC_Table.php(689): Contao\Database\Statement->execute()
#2 /home/www/xxx/html/website/system/modules/core/classes/Backend.php(650): Contao\DC_Table->create()
#3 /home/www/xxx/html/website/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#4 /home/www/xxx/html/website/contao/main.php(20): Contao\BackendMain->run()
#5 {main}

Best Regards,
Joc

**Comment by qzminski** [comment]
That bug has been fixed on the develop branch, you can apply a patch:

https://github.com/codefog/contao-events_subscriptions/blob/f09049787766860e5508bedac14fe72321e5caff/dca/tl_calendar_events_subscriptions.php#L119

**Comment by b-fender** [comment]
Thank You VERY much!

**Comment by b-fender** [comment]
i tried it with

'default'                 => '0',
This was also working.
But Your Choice is better ;-)
