### ISSUE TITLE
Make settings mandatory on override

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#20]
Actually our teachers, who create/copy events, sometime have to change the basic settings from calendar archives. Mostly max numbers for an event.

Very often they just check "override, then change the max number of subscriptions and forget the rest. This means....users is unchecked and there will be empty subscriptions if somebody subscribes.

All fields in eventsettings should be mandatory (user groups, max subscribers, both time fields to end/unsubscribe) when override is checked.

greetings Frank

**Comment by qzminski** [comment]
Unfortunately that will not be possible, as the fields can also take empty values (e.g. unsubscribe/subscribe end time).

**Comment by Kahmoon** [comment]
OK
