### ISSUE TITLE
Index "enableReminders" does not exist in array

### ISSUE THREAD

**Issue by reluem** [codefog/contao-events_subscriptions#21]
With #19 and the optional event reminders, there is a new error in v2.3.2:
If the option to get a reminder in the archive is deactivated, the frontend throws an error:
`Index "enableReminders" does not exist in array`

Once enabled, it works again.

**Comment by Kahmoon** [comment]
Oh thanks...i didn´t check this!

**Comment by qzminski** [comment]
Can you try if 05759dbce917471213d16089b0535f8c332b36ea solves the problem?

**Comment by reluem** [comment]
yes, works. Thanks for the quick update!

**Comment by qzminski** [comment]
Perfect, 2.3.3 has been just released :+1:
