### ISSUE TITLE
Overview of subscriptions of an archive for admins

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#22]
This is a suggestion for an enhancement.

An additional button per calendar archive to list all subscriptions (like in an event itself) over all events of this archive would be really nice. Especially when you work with several archives. In my case, every 2 months 4 new archives :)

That's why sometimes I have to look for a subscription quite "long".

I hope I explained that reasonably well

Greetings Frank

**Comment by Kahmoon** [comment]
Hi Kamil,

can i ask for this feature again? Maybe with payed support? You can send me an offer if you want.

Frank

**Comment by Kahmoon** [comment]
Heyho, may i ask for this request again? :-)

Frank

**Comment by Aybee** [comment]
Would be nice, if the events listview in BE has columns. Then you can bring those columns in there
```
Subcritions - Waitinglist
3/6         -
6/6         - 2/6
```
I saw similar with the old simple_event_registration.

**Comment by qzminski** [comment]
I have came up with something like on the image attached. Any suggestions?

<img width="1210" alt="Zrzut ekranu 2020-07-23 o 15 54 04" src="https://user-images.githubusercontent.com/193483/88294602-bfce1380-ccfc-11ea-963a-1c5d5e5e8538.png">

**Comment by Kahmoon** [comment]
this looks pretty awesome!!!

**Comment by DavidStae** [comment]
Dear Kamil
   This overview looks great. However, the number of participants in our case is relevant, when a member subscribes and wants to bring guests along. Your overview does not help in this respect. 
    At the moment we help ourselves by using fake members. If a member wants to bring guests along, the member will have to login multiple times under different profiles (their own and the fake ones) to subscribe also their guests for the event.
   Is my understanding correct, that this issue has not yet been addressed yet?
   Please advise. 
   Many thanks
   David
--
David Staehelin | 079 619 11 72 | von unterwegs

**Comment by qzminski** [comment]
@DavidStae I believe that your issue is being discussed already here https://github.com/codefog/contao-events_subscriptions/issues/16

**Comment by Aybee** [comment]
Looks great 👍 

And yes, @DavidStae is in the wrong ticket. He's new on Github 🙋‍♂️ 😁

**Comment by Kahmoon** [comment]
Thanks Kamil!!!! The new overview is fucking great!!!!!!! (sorry for my wording but i quite exited!) 👍
