### ISSUE TITLE
Variable link to subscribed event

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#23]
Feature Request

Hi Kamil,

is it possible to get a variable which can be used in confirmation mail which contains a direct link to the event? ##event_id## and ##event_alias## ist not enough in my case.

In my case.....there are several archives on different structures...the link is not static for every event :-(

Maybe full url in a hidden field on subscribe form?
`<input name="eventurl" type="hidden" value="{{env::request}}">`

Greetings Frank

**Comment by Kahmoon** [comment]
Problem solved. Maybe you can put this in your documentation "Notofications".

This creates a correct link!
`{{event::##event_id##}}`

**Comment by qzminski** [comment]
Thanks, changed in 04dc26c.
