### ISSUE TITLE
Var dump with error

### ISSUE THREAD

**Issue by Acta2000** [codefog/contao-events_subscriptions#26]
Hello,  

i tried to make some Changes to the Template:
Id like to show how many places are avaible for the event

So i set `<?php dump($this->getData()) ?>` to the template to see whats avaible.

But i get the  error:

`[2019-07-23 17:22:35] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"dump\" from the global namespace. at D:\\htdocs\\map\\templates\\event_list_subscribe_eigen.html5:2)"} []`

**Comment by qzminski** [comment]
This is outdated and works only for dev environments. I will update the README.

Meanwhile please try to use `<?php $this->dumpTemplateVars() ?>`

**Comment by Acta2000** [comment]
OK found my error.

**Comment by Acta2000** [comment]
Little Question:

Is there an example for a good working template?

**Comment by qzminski** [comment]
Please check the `event_list_subscribe` template.

**Comment by Acta2000** [comment]
Okay is there a possible way to say:
If the maximum of subscriptions is reached an there is an Waiting-List
dont show ="register" show ="rigister to Waiting-List"

Now i using:
`<div class="max_plaetze"><span class="legende">Maximale Platzanzahl:</span> <?php echo $this->subscription_maximum; ?></div>   
<div class="ver_plaetze"><span class="legende">Bisher erfolgte Anmeldungen:</span> <?php echo count($this->subscribers['subscribers']); ?></div>
`

Maybe something Linke: 

`if (count($this->subscribers['subscribers']) == $this->subscription_maximum) 
echo "register to Waiting-List"

**Comment by qzminski** [comment]
The code you posted should work just fine. I assume it does not for some reason?

**Comment by Acta2000** [comment]
I was just thinking about a other solution.
