### ISSUE TITLE
Enhancement: E-Mail reminder for admin/teacher

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#27]
An additional field (e.g. admin or teacher mail) in event subscription mask to send another reminder to the teacher/admin/contact of an event. Actually the reminder sends only to the subscribers.

All of our teachers/admin are also frontend members. So a member selector instead of plain textfield (email) would be the "super nice solution".

Greetings Frank

**Comment by qzminski** [comment]
This requires a custom solution for your project and thus it will not be a feature of this open source extension.

**Comment by Kahmoon** [comment]
OK. i wrote you an email
