### ISSUE TITLE
Add own fields safely for update

### ISSUE THREAD

**Issue by sevenfour66** [codefog/contao-events_subscriptions#28]
Hello qzminski, 

first a big thank you for the extension. I have a question. I would like to extend the extension with one more field e.G. "field_school".

I attach the folder 
`/app/Resources/contao/dca/` 
and add the field in the 
`tl_calendar_events_subscription.php`

That's works fine and the field is also available in the backend.

To make the field available in the frontend and for the Export, the `GuestSubscription.php` and the `Exporter.php` must be overwritten. How does this work safe for update? 

If i do that in the core files under:

`/vendor/codefog/contao-events_subscriptions/src/Codefog/EventsSubscriptions/Subscription/GuestSubscription.php`

`/vendor/codefog/contao-events_subscriptions/src/Codefog/EventsSubscriptions/Exporter.php`

it works fine, but this procedure is not safe for update. Can you tell me how to do it right?

Thanks
sev

**Comment by qzminski** [comment]
I suggest that you simply overwrite the `GuestSubscription` type as shown in the [developers documentation](https://github.com/codefog/contao-events_subscriptions/blob/master/docs/08-developers.md).

**Comment by sevenfour66** [comment]
I have read the manual, but i do not understand in which folder must the modified file `GuestSubscription.php` be copied.

And what must be entered in the `config.php` for the modified file to be called? This entry leads to the original file:

`\Codefog\EventsSubscriptions\Services::getSubscriptionFactory()->add(
    'guest',
    'Codefog\EventsSubscriptions\Subscription\GuestSubscription'
);`

Sorry for the beginner questions and thanks to your help

**Comment by qzminski** [comment]
Well, basically you have to create your custom extension or put files as a regular Symfony app, then override subscription type in config to point to your class and finally adjust the necessary code. Unfortunately I am not able to provide you a ready-to-use code as it's not a place for free code services. If you are new to PHP I suggest that you hire an experienced developer that will guide you through the development of this part of the project.
