### ISSUE TITLE
Enahancement for #14: Show allowed member group(s) for subscription in Eventdetails

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#29]
Hey Kamil,

due to our advanced subscription system (made in https://github.com/codefog/contao-events_subscriptions/issues/14) we can choose which member groups are allowed to subscribe. Super nice! 

But sometimes other groups can see this event too but are not allowed subscribe and some of them don´t understand why. Even i put a static explanation next to it....

How can I show this data of allowed member groups in the event detail/subscription form. Is there a variable I didn´t see in the documentation?

A good solution via template could be another line/variable next to "free slots". This should also work if the subscription is not overwritten, so rights from calendar archive should be available (like max registration user, time etc. )

Greetings Frank

**Comment by qzminski** [comment]
Which template would you like to display it in?

**Comment by Kahmoon** [comment]
Probably in event_full_registration.html5 would be the best place.

**Comment by qzminski** [comment]
Please try this snippet of code:

```php
<?php if (($config = \Codefog\EventsSubscriptions\EventConfig::create($this->id))->hasMemberGroupsLimit() && count($memberGroupIds = $config->getMemberGroups()) > 0 && ($memberGroups = \Contao\MemberGroupModel::findMultipleByIds($memberGroupIds)) !== null): ?>
    <p>Only the following member groups are allowed to subscribe: <?= implode(', ', $memberGroups->fetchEach('name')) ?></p>
<?php endif; ?>
```

**Comment by Kahmoon** [comment]
Yep, this is working pretty good. Where can i find the translation for it?

**Comment by Kahmoon** [comment]
One last question. Is it possible to use this variables also in the language files?

$GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeNotAllowed']  = 'my text - allowedgroups'.

**Comment by qzminski** [comment]
Either that or just use the language insert tags `{{iflng}}`.
