### ISSUE TITLE
Variable for free slots left in template

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#30]
Hi Kamil,

in want to show a special text when all slots are full. I found an inserttag {{events_subscriptions::total_limit_left}} in your documentation. 

This inserttag is not working in template (eventsubscription_form.html5)

I tried also to use replaceInserttag

`<?php echo $this->replaceInsertTags('{{events_subscriptions::total_limit_left}}'); ?>`

Dump <?php $this->dumpTemplateVars() ?> also don´t contains a value for this

Can we get a variable which is working in templates?

Greetings Frank

**Comment by Kahmoon** [comment]
May i push this one? :-)

**Comment by qzminski** [comment]
This insert tag is available only for the logged in users. Is that the case for you?

**Comment by qzminski** [comment]
It seems to work fine for me. What limit values did you set in the member group settings?

**Comment by Kahmoon** [comment]
Maximum Limit is show but i need the value from total_limit_left

In archive max number of 25 is set but the total_limit_left has no output. Doesn´t matter if the are registration already.

`<?php echo $this->replaceInsertTags('{{events_subscriptions::total_limit_left}}'); ?>`

**Comment by qzminski** [comment]
I am asking you about the limit values in the **member group** settings which this tag relates to: https://github.com/codefog/contao-events_subscriptions/blob/master/docs/03-advanced.md#limit-subscriptions-per-member-andor-member-group

**Comment by Kahmoon** [comment]
Its set to 25 in the archive and/or in the event itself. No difference

**Comment by Kahmoon** [comment]
Ahh OK...i think we have a misunderstanding here. I found a limit in Member Settings of Contao.

What i need is the free slots of an event. For Example max subscriptions 25 and there a re already 5 members subscribed. I need a variable which shows me the remeinaing free slots - In this case 20. 

For my understand total_limit_left is what i need.

**Comment by Kahmoon** [comment]
Those variables give me an output but i think its wrong :-)

Testevent with 10 max subscriptions:

$this->subscriptionMaximum = 1

$this->subscribers
with no registrations: 0
with one registration: 2

Both values makes no sense to me? :-)

**Comment by qzminski** [comment]
Sorry it should be `$this->subscription_maximum` and `count($this->subscribers['subscribers'])` 🤦🏻‍♂️

**Comment by Kahmoon** [comment]
Yep! Perfect. Thanks

Maybe put this is the documentation? I think remaining slots (overall) is a usefull information.

**Comment by qzminski** [comment]
I will consider putting it in the documentation, yet it is always useful to check available data using `<?= $this->showTemplateVars() ?>`.

**Comment by Kahmoon** [comment]
I did but i couldn´t figure it out from this data

**Comment by qzminski** [comment]
Sorry, is `$this->subscriptionMaximum` not the same for you as `$this->subscription_maximum` ??

**Comment by Kahmoon** [comment]
Seems not. I just got the output 1 with $this->subscriptionMaximum

**Comment by qzminski** [comment]
And what does the `$this->subscription_maximum` print out?

What are your settings for maximum subscription for that event AND for the calendar containing that event?

**Comment by Kahmoon** [comment]
Event with 25 max (archive settings). No overwriting in event.
$this->subscriptionMaximum = shows 25
$this->subscription_maximum 

Event with (calendar 25) and overwriting (12)
$this->subscription_maximum = shows the maximum when i overwrite archive settings
$this->subscriptionMaximum = shows 12

By the way...$this->subscription_maximum keeps the custom value even if i deactivate overwriting. Is this supposed to be?

**Comment by qzminski** [comment]
In the earlier posts you said `$this->subscriptionMaximum` prints `1`? So what is the final value?

Actually I have to correct myself again: `$this->subscriptionMaximum` should be used because it considers the overwrite values in the event.
