### ISSUE TITLE
Hard-Coded "enableReminders"-legend

### ISSUE THREAD

**Issue by Acta2000** [codefog/contao-events_subscriptions#31]
Hello Kamil, 

i has activate the option e-mail reminder. In the frontend it now shows the checkbox. But above there is a legend "enable-Reminders"

I have vardumb the position:

```
enableReminders" => array:11 [
              "id" => "enableReminders"
              "name" => "enableReminders"
              "strField" => "enableReminders"
              "strTable" => ""
              "label" => "enableReminders"
              "description" => null
              "type" => "checkbox"
              "dataContainer" => null
              "allowHtml" => false
              "options" => array:1 [
                0 => array:2 [
                  "value" => 1
                  "label" => "Eine Erinnerung für diese Veranstaltung erhalten"
                ]
              ]
              "value" => 1
            
```
Can you say me how i can disable the Label or better set a othner labelname?

The html output is:

    
```
    <fieldset id="ctrl_enableReminders" class="checkbox_container">

          <legend>
                  enableReminders              </legend>
    
    
    <input type="hidden" name="enableReminders" value="">

          
              <span><input type="checkbox" name="enableReminders" id="opt_enableReminders_0" class="checkbox" value="1" checked=""> <label id="lbl_enableReminders_0" for="opt_enableReminders_0">Eine Erinnerung für diese Veranstaltung erhalten</label></span>
      
          
  </fieldset>
```
Of course i can use #ctr_enableReminders legend display:none  but i like do this the clean way

**Comment by Kahmoon** [comment]
You can change the label /contao/languages/de/defaulz.php

`$GLOBALS['TL_LANG']['MSC']['events_subscriptions.enableReminders']  = 'Die Erinnerungsfunktion aktivieren';
`

**Comment by Acta2000** [comment]
![Unbenannt](https://user-images.githubusercontent.com/12759828/66986532-64149100-f0bf-11e9-9c11-3f6b0a8095ac.JPG)

its just change the Checkbox label. 

I think i have to change the <legend>

**Comment by Kahmoon** [comment]
ok, just checked my installation. I hide this element via CSS. removing it from a template (eventregistration_form.html5) would be better....indeed....

`#ctrl_enableReminders legend {
    display: none;
}`

**Comment by qzminski** [comment]
That must have happened in one of the latest Contao core updates. The easiest and acceptable solution is to hide it just with CSS. If you still want to change the markup though, you should create a custom `form_checkbox.html5` template.
