### ISSUE TITLE
Code bug in waiting list listing ul

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#33]
Hi,

the list of subscribers in event detail view at waiting list has a wrong closing ul. It contains a blank "< /ul>".

```
<ul>
<li>Frank XXX</li>
&lt;	/ul&gt;

```
Template event_full_registration.html5

Greetings

**Comment by qzminski** [comment]
This looks like a custom template which is not a part of the extension.

**Comment by Kahmoon** [comment]
OH? Ok! Thx
