### ISSUE TITLE
Notification update waitinglist does not support variable "unsubscribe_link"

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#34]
Hi,

i wanted to add the unsubscribe link in notification mail of waiting list changes but the system shows an error.

> Die folgenden eingesetzten Tokens werden vom Notification-Typ nicht unterstützt: ##unsubscribe_link##.

VG Frank

**Comment by qzminski** [comment]
This issue has been fixed in 2.6.1.

**Comment by Kahmoon** [comment]
thanks!
