### ISSUE TITLE
Reminder Mail only when event active

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#35]
Hi Kamil,

actually we sometimes have events canceled even people are already subscribed. The daily mail cron does not check if event is active or not. When event is disabled, there should **not be** any reminder mail for it. Today two people drove 40km to find out that this event was canceled ;-P

Greetings

**Comment by qzminski** [comment]
What do you actually mean by "active event"? Do you mean if the event is published?

**Comment by Kahmoon** [comment]
Yes, active = published. Sorry
