### ISSUE TITLE
Enhancement: Adding CSS class to subscribed events in event listing and calendar full 

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#36]
Hi Kamil,

actually in calendar full oder calendar list for students its hard to see if they are already subscribed to an event or not. Yes, there is "my events" module but this isn´t used to see all future events of the school.

It would be super nice when a css class e.g. "subscribed" is added to calendar listing and calendar full module list. Then you can add a custom color, icon or what ever to an event without to force the people into the detail view to see if they are subscribed or not.

I don´t know how difficult this would be. If its a bigger change, let me know, then we can do a payed customization again.

Frank

**Comment by qzminski** [comment]
This has been released in 2.8.0.
