### ISSUE TITLE
Reminders are sent every day, also for event in the past

### ISSUE THREAD

**Issue by rustykowski** [codefog/contao-events_subscriptions#37]
Contao 4.9.1, events_subscriptions 2.7.1:
Members get reminder-notifications for all subscribed events every day at 12:00, including subscribed events in the past.
My calendar-settings are:
![image](https://user-images.githubusercontent.com/1775048/76209338-f13cbb80-6201-11ea-8721-1c69bbf880ea.png)

**Comment by Kahmoon** [comment]
Hmm thats strange. I don´t have this behaviour. Reminders are sent correct 1,3

Event is on tuesday - reminder was sent saturday and today

The only difference is Contao 4.8.8

**Comment by Kahmoon** [comment]
Maybe this change on version 2.7.1 could be the reason
https://github.com/codefog/contao-events_subscriptions/commit/0c91311119076f0c6b9f87bf4c5c017bbe21177c

**Comment by qzminski** [comment]
This should be fixed in 2.7.2 :+1:
