### ISSUE TITLE
New envelope icon on events 2.7.2

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#38]
I just updated to V 2.7.2. In backend events there is a new enveloge icon to send notification manually but you cannot choose a notification type.

Is this a new feature?

VG Frank

**Comment by qzminski** [comment]
This is a new feature introduced in 2.7. You should be able to choose the notification once you create the notification of `Event notification` type. For more details see: https://github.com/codefog/contao-events_subscriptions/blob/master/docs/06-notifications.md#notification-types-and-their-purposes

**Comment by Kahmoon** [comment]
This mail is send to all members of the group or just to all subscribers?

**Comment by Kahmoon** [comment]
We did some restriction to member groups. This nice new feature should consider this rights.

This notification should not be possible to send to Group B which cannot see events from group A

**Comment by Kahmoon** [comment]
Another small problem is the mail token.

"##subscription_firstname##" is not allowed in this mail template but this mail is send to members. So this variable should be available!?
