### ISSUE TITLE
array_key_exists() error on install in 4.9

### ISSUE THREAD

**Issue by reluem** [codefog/contao-events_subscriptions#39]
contao 4.9 throws an error when installing the module
```
Warning: array_key_exists() expects parameter 2 to be array, null given in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 401
```

my composer.json includes (for testing) only core modules and this extension
```"require": {
    "php": ">=7.1",
    "contao/calendar-bundle": "^4.7",
    "contao/manager-bundle": "4.9.*",
    "contao/news-bundle": "^4.7",
    "codefog/contao-events_subscriptions": "^2.8"
  }
```
What could be the problem here? unfortunately, the error logs are not giving any hints…

**Comment by qzminski** [comment]
Sorry but I am unable to reproduce the problem. Please try running the composer update/install command with the `-vvv` flag, that should tell more about the error.

**Comment by reluem** [comment]
hey, I was a bit unprecise. The issue occurs during the cache warming for the prod env (either during install, or manually). The `-vvv` flag only shows details on the install process, not the cache 

>  % vendor/bin/contao-console cache:clear --env=prod
> // Clearing the cache for the prod environment with debug false                                                        
> 
> PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 401
> 
> Warning: array_key_exists() expects parameter 2 to be array, null given in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 401


If I remove codefog/contao-events_subscriptions, the cache warming is fine again.

**Comment by qzminski** [comment]
Can you the run this command please?

```
vendor/bin/contao-console cache:clear --env=prod -vvv
```

If that does not work please try the `dev` environment as well:

```
vendor/bin/contao-console cache:clear --env=dev -vvv
```

**Comment by reluem** [comment]
Here's the result for the dev environment. 
Let me know if I can do anything else!

>  // Clearing the cache for the dev environment with debug true                                                          
> 
>  // Warming up cache...                                                                                                 
> 
> 15:07:53 DEBUG     [php] Warning: include(xxx/var/cache/de_/appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php): failed to open stream: No such file or directory
> [
>   "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext^ {
>     +count: 1
>     -severity: E_WARNING
>     trace: {
>       ./vendor/symfony/http-kernel/Kernel.php:539 { …}
>       ./vendor/symfony/http-kernel/Kernel.php:539 { …}
>     }
>   }
> ]
> 15:07:53 DEBUG     [php] Warning: include(): Failed opening 'xxx/var/cache/de_/appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php' for inclusion (include_path='.:/usr/local/Cellar/php/7.3.9_1/share/php/pear')
> 15:07:59 DEBUG     [php] Notice: Undefined index: foreignKey
> [
>   "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext^ {
>     +count: 1
>     -severity: E_NOTICE
>     trace: {
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:409 { …}
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:120 { …}
>     }
>   }
> ]
> 15:07:59 DEBUG     [php] Notice: Undefined index: dataContainer
> [
>   "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext^ {
>     +count: 1
>     -severity: E_NOTICE
>     trace: {
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:381 { …}
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:120 { …}
>     }
>   }
> ]
> 15:07:59 DEBUG     [php] Notice: Undefined index: dataContainer
> [
>   "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext^ {
>     +count: 1
>     -severity: E_NOTICE
>     trace: {
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:387 { …}
>       ./vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:120 { …}
>     }
>   }
> ]
> 
> In DcaExtractor.php line 401:
>                                                                            
>   [ErrorException]                                                         
>   Warning: array_key_exists() expects parameter 2 to be array, null given  
>                                                                            
> 
> Exception trace:
>   at xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:401
>  Contao\DcaExtractor->createExtract() at xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:120
>  Contao\DcaExtractor->__construct() at xxx/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:142
>  Contao\DcaExtractor::getInstance() at xxx/vendor/contao/core-bundle/src/Cache/ContaoCacheWarmer.php:186
>  Contao\CoreBundle\Cache\ContaoCacheWarmer->generateDcaExtracts() at xxx/vendor/contao/core-bundle/src/Cache/ContaoCacheWarmer.php:92
>  Contao\CoreBundle\Cache\ContaoCacheWarmer->warmUp() at xxx/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:97
>  Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at xxx/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:196
>  Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at xxx/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129
>  Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at xxx/vendor/symfony/console/Command/Command.php:255
>  Symfony\Component\Console\Command\Command->run() at xxx/vendor/symfony/console/Application.php:1019
>  Symfony\Component\Console\Application->doRunCommand() at xxx/vendor/symfony/framework-bundle/Console/Application.php:97
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at xxx/vendor/symfony/console/Application.php:271
>  Symfony\Component\Console\Application->doRun() at xxx/vendor/symfony/framework-bundle/Console/Application.php:83
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at xxx/vendor/symfony/console/Application.php:147
>  Symfony\Component\Console\Application->run() at xxx/vendor/contao/manager-bundle/bin/contao-console:38
>

**Comment by qzminski** [comment]
Nothing suspicious here. Can you send me your `composer.json` and `composer.lock` files (e.g. to info@codefog.pl)? Also please let me know which PHP version you have exactly.

**Comment by qzminski** [comment]
The composer files you have sent me work just fine for me under the very same PHP version:

```
kamil@MacBook-Pro-Kamil tmp % /Applications/MAMP/bin/php/php7.3.9/bin/php vendor/bin/contao-console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


kamil@MacBook-Pro-Kamil tmp %
```

warming up as well:

```
kamil@MacBook-Pro-Kamil tmp % /Applications/MAMP/bin/php/php7.3.9/bin/php vendor/bin/contao-console cache:warmup --env=prod

 // Warming up the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.


kamil@MacBook-Pro-Kamil tmp %
```

Are you sure you don't have any custom code in your setup?

**Comment by reluem** [comment]
I’ve just tried again in another system, same issue. 
but then I created a new installation from scratch:

> composer create-project contao/managed-edition . 4.9
> composer require codefog/contao-events_subscriptions

and it worked fine. 

So I'm assuming also a system error on my side then…

I'll investigate further, thanks!

**Comment by reluem** [comment]
Actually the error occurs once I connect the database, maybe some missing DCA definitions (the error is hinting at this).

**Comment by qzminski** [comment]
Yes you would likely half to debug DcaExtractor at the mentioned line to see which table and field it crushes at.

**Comment by reluem** [comment]
Well, the error is happening in  tl_opt_in_related => relId and tl_member_group  => subscription_periodRef

table: tl_opt_in_related
field: id
field: pid
field: relTable
field: relId

Warning: array_key_exists() expects parameter 2 to be array, null given in /Users/lucas/PhpstormProjects/BBR/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 376


table: tl_member_group
field: id
field: tstamp
field: name
field: redirect
field: jumpTo
field: disable
field: start
field: stop
field: subscription_enableLimit
field: subscription_totalLimit
field: subscription_periodRef

Warning: array_key_exists() expects parameter 2 to be array, null given in /Users/lucas/PhpstormProjects/BBR/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 376
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /Users/lucas/PhpstormProjects/BBR/vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php on line 376


Any idea how to fix this?

**Comment by qzminski** [comment]
Thanks for debugging this! Please try to update the extension to 2.8.1 and see if `tl_member_group. subscription_periodRef` field is affected again.

**Comment by reluem** [comment]
all fine now, thanks for the update!
