### ISSUE TITLE
empty subscribeMessage 

### ISSUE THREAD

**Issue by reluem** [codefog/contao-events_subscriptions#40]
Hi Kamil, 

facing some issues. 
It used to work for me that after subscribing to an event, the page reloads and the _subscribeMessage_ is shown.

This stopped working now (I don't know since when, unfortunately). The 
$this->subscribeMessage is always empty.

Do you have an idea? 
my redirect page is set to the page of the eventlist

Contao 4.9.2
latest contao-events_subscriptions

**Comment by qzminski** [comment]
It works for me just fine. Did you perhaps override the `$GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeConfirmation']` language variable?

**Comment by reluem** [comment]
hey there, I'm trying to investigate the problem a bit. 

no overrides from my side. I'm assuming that the subscribe message is set via _FlashMessage.php_ as event-subscribe-message

in that case, no message is set in my installation on submission of the form. 

is there something I could check on my installation?

**Comment by qzminski** [comment]
Just before the line below you can add the code `var_dump($message);exit;` and see what it outputs.

https://github.com/codefog/contao-events_subscriptions/blob/master/src/Codefog/EventsSubscriptions/FlashMessage.php#L30

**Comment by reluem** [comment]
so here I see the message correctly being generated. 

https://github.com/codefog/contao-events_subscriptions/blob/9c267bd3a260e810219b78fd36e6032e980789cd/src/Codefog/EventsSubscriptions/FrontendModule/SubscriptionTrait.php#L65

afterwards, the redirect happens, but the part of setting the message never happens: https://github.com/codefog/contao-events_subscriptions/blob/9c267bd3a260e810219b78fd36e6032e980789cd/src/Codefog/EventsSubscriptions/FrontendModule/SubscriptionTrait.php#L174 (+ the line you mentioned).

if I move this part up inside the redirect, it seems to be working fine

```
if (($page = PageModel::findPublishedById($pageId)) !== null) {
            Services::getFlashMessage()->set($message, $eventId); //copied here from below
            Controller::redirect($page->getFrontendUrl());
        }
```

**Comment by qzminski** [comment]
Thanks for debugging. It looks like that you have a redirect page set in your module. In that case the confirmation message is not set because by design the target page should display a subscription confirmation instead of a flash message.

If you redirect to the same page, then you should just remove the page value from that field and it should all be fine – the page will just reload and a flash message will be displayed.

**Comment by reluem** [comment]
yes, you are right. that is indeed the intended behavior. 
removing the redirect pages correctly shows the subscribe message. 

I am still wondering though at what point an unsubscribe message is triggered? ideally once I click the link to unsubscribe, I would like to show the unsubscribe message in the place of the subscribe message. 
Do I have to implement a custom onunsubscribe class for that? 

Thanks!

**Comment by qzminski** [comment]
It should work exactly the same as the subscribe message – if no redirect page is set, than it should automatically reload the page and display a flash message `$GLOBALS['TL_LANG']['MSC']['events_subscriptions.unsubscribeConfirmation']`.

**Comment by reluem** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/17430489/82794520-e4c81680-9e72-11ea-8cc7-e6d5aa35e455.png">
so I would set the event list page here? 

the redirect happens, but no message is shown

**Comment by qzminski** [comment]
You have to leave this field empty, just like on the screenshot. In that case the page will reload and the message should be shown.

**Comment by reluem** [comment]
could it be that the unsubscribe message is only implemented for members and not for guests? 

"the message should be shown“ in the same module as the confirmation message, right? so I need to point the unsubscribe link to the page where the eventlist module is located

**Comment by qzminski** [comment]
Well the guests cannot unsubscribe, so how can I they see that message? 😉

**Comment by reluem** [comment]
via the unsubscribe link that I send in the mail. 
I thought the unsubscribe message would also be shown if I open my list module page with the ?event_unsubscribe token

**Comment by qzminski** [comment]
Ah, I see the problem now. Yes, the unsubscribe confirmation will **not** be displayed if you unsubscribe via e-mail link (no matter member or guest). 

At the moment the only option is to choose an unsubscribe page in the **calendar settings**, which a user would to be taken when unsubscribing via e-mail link.

**Comment by reluem** [comment]
okay, all clear now. thank you!
