### ISSUE TITLE
New mail function only to allowed member groups of the event

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#41]
Hi Kamil,

the new feature to inform members about new events is great! But actually all groups are listed. Its kinda dangerous to send this mail to member groups which cannot even subscribe or even see this event (In our case we have about 50+ Member groups with kinda similar names). A missclick is done really quickly and this mailing is send to many wrong students :D

A real enhancement would be:
**Subscription set to  specific member group(s)**
Only the groups which are actually allowed to subscribe to this event should be listed.

**Subscription set to member in general**
If there is just "member" set to subscribe, then it should list all groups

I hope i could explain this problem. This would help us and probably other users a lot.

Greetings Frank

**Comment by Kahmoon** [comment]
May i bump this a bit? :-)

**Comment by Kahmoon** [comment]
Any plans about this issue here? Maybe payed change if this would prioritise this one a bit? :)

**Comment by qzminski** [comment]
How about I split the current member group list into two:

1. member groups that can actually subscribe;
2. all other member groups.

What do you think?

**Comment by Kahmoon** [comment]
Sounds good. Normally (2) is not needed because nobody gets a mail if they cannot subscribe. But if this will be easier....im fine with it. I just want to avoid my customer so send mails so completely wrong students :D

**Comment by qzminski** [comment]
Implemented in 0f0f055. It will be a part of 2.9.0 release.

![2020-07-23 at 17 30](https://user-images.githubusercontent.com/193483/88305849-4806e580-cd0a-11ea-8ef5-7c826c536f04.png)

**Comment by Kahmoon** [comment]
Thx!

**Comment by Kahmoon** [comment]
Hi,

may i ask when a release of 2.9 is planed?

Frank

**Comment by qzminski** [comment]
It will be released once #45 is merged.
