### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-events_subscriptions#42]
Hello Kamil,

I like to do some revision and improvements to the german language based on your english version. Is it on transifex, shall I do a pull request or shall I simply send you the new files?

**Comment by qzminski** [comment]
Please provide a pull request, thank you :+1:

**Comment by Aybee** [comment]
OK

**Comment by Aybee** [comment]
Done #43

**Comment by qzminski** [comment]
Thanks a lot!

**Comment by Aybee** [comment]
Dito 🥇
