### ISSUE TITLE
Waitinglist mail only sent when unsubscribe from FE not from BE

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-events_subscriptions#44]
Hello Kamil,

I tested the waitinglist mail and it worked when a member unsubscribes via FE. Then the waitinglist member who now gets promoted to the subscribers list gets the waitinglist mail.

But: When I delete a subscriber manually via BE then the promoted waitinglist member doesn't get this mail.

Then in the system log the email sent message also is missing.

ps I did not create neither an unsubscribe nor a subscribe message in notification center as the customer don't need this. Therefore the system log sometimes shows such messages
```
[15.07.2020 13:15] Could not find any messages for notification ID 9
[15.07.2020 13:15] Could not find any messages for notification ID 10
```
But it seems to work. I don't think that the missing unsubscribe and subscribe message have an influence to the waitinglist promotion emails.

**Comment by Kahmoon** [comment]
I cannot verify this. When i manage subscribers via backend, all mails are send. I have set up both of this mails.

**Comment by Aybee** [comment]
Ok, we first try it with valid subscriber notifications and will come back.

**Comment by Aybee** [comment]
Now after setting up the subsribe and unsubscripe notification it seems to work. David does some tests and reported that all is fine.

So in the end using those two notification is a must even if you don't need them.
