### ISSUE TITLE
New german translation comming soon

### ISSUE THREAD

**Issue by Aybee** [codefog/contao-events_subscriptions#50]
I will do the new german language variables within the next days. Maybe today.

**Comment by Kahmoon** [comment]
Where can i change some values of german translation?

`$GLOBALS['TL_LANG']['MSC']['events_subscriptions.subscribeWaitingList']    = 'Auf eine Warteliste setzen';`

Makes no sense....it should be "Auf **die** Warteliste setzen"

**Comment by qzminski** [comment]
@Aybee can you confirm what @Kahmoon says? When do you plan to provide the German labels?

**Comment by Aybee** [comment]
I will start just now.

@Kahmoon Ja, damit war ich auch nicht glücklich. Ich denke, wo ich jetzt die neuen Variablen übersetze, werde ich dies auch nochmal ändern.

Told Kahmoon that I'm also not happy with that and will change this.

Contao 4.9: I think you can do changes within ROOT/contao/languages/de/default.php
