### ISSUE TITLE
Last notification date gets copied with event

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#51]
Hi Kamil,

i probably just found a small bug. I copied an event where i did send a notification to users. When i click on mail options in the new event it says "Last notification was sent on 21.07.2020 10:53". 

But this event was created yesterday by a copy from an event in july.

I assume that this timestamp gets copied, it should be cleared at the new event.

Frank

**Comment by qzminski** [comment]
Should be fixed in 2.8.5.
