### ISSUE TITLE
Enhancement of the new feature show subscriptions overview

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#54]
I love the new overview of subscriptions to every event! I have three suggestions for small tweaks.

1. In this overview there should be the mail button like in event listing too. Actually there is only the subscriber button
2. Event titles should be a link to the event settings....or maybe this also could be a contao core "edit" (class editheader) icon on the right side
3. The date column does have a very early line break...even on big screens its gets a line break quite early which is not neccessary see screenshot: 
<img width="1477" alt="Bildschirmfoto 2020-11-04 um 11 22 07" src="https://user-images.githubusercontent.com/6390770/98099567-06044880-1e90-11eb-943a-fd407c5adc43.png">
<img width="1168" alt="Bildschirmfoto 2020-11-04 um 11 22 15" src="https://user-images.githubusercontent.com/6390770/98099577-07ce0c00-1e90-11eb-95f2-72c3d9a6ddba.png">

Keep up the good work.

Frank

**Comment by Kahmoon** [comment]
Also a range or pagiantion would be good. Actually i get all events listed (until 2013) which is quite a lot :D

**Comment by Aybee** [comment]
Use the "Show" filter to limit the visible entries. Or/and go to BE settings and set "Items per page" to the default 30. Or/and go to your account settings and use "Clear cache - Purge data - Session data".

_Please don't show images on ibb.co, you can drag your image directly here into the editor._

**Comment by Kahmoon** [comment]
Sorry, i did miss your answer

>"Use the "Show" filter to limit the visible entries. "

There are no filter options in overview

>Or/and go to BE settings and set "Items per page" to the default 30

That would affect every other listing in my installation which wouldn´t be a good workaround at all

> Please don't show images on ibb.co, you can drag your image directly here into the editor.

Didn´t know....have to try next time

@qzminski Any chances to get enhancement 1 & 2? I Think this wouldn´t be a super big change but a real **big** enhancement:-)

greetings

**Comment by qzminski** [comment]
Implemented in 2.10.0.

**Comment by Kahmoon** [comment]
👍🏻🤟🏻

**Comment by Kahmoon** [comment]
Can i control the amount of the pagiantion? Maybe via config? Core value in settings seems to be ignored.

**Comment by qzminski** [comment]
Please update to 2.10.1.

**Comment by Aybee** [comment]
> Did you test this new listing!?

Maybe I did not test it and assumed there is a Show Limit like on other pages. Sorry.

**Comment by Kahmoon** [comment]
That would be nice to have the default core filters. But its finde now. Thanks again!
