### ISSUE TITLE
Way to remove standard column in Export

### ISSUE THREAD

**Issue by tsarma** [codefog/contao-events_subscriptions#56]
Hi there, Thanks for the extension.

Can you please provide a way to remove columns like `Event title`, `Event start`,  `Event end`,  `Subscription type`, `Waiting list`  from Export? 
Or is there already one, which I'm not aware of at the moment.

**Comment by qzminski** [comment]
I think you should be able to do that using `onExport` event: https://github.com/codefog/contao-events_subscriptions/blob/master/docs/08-developers.md#onexport

**Comment by tsarma** [comment]
Yes, with the Hook I can get indeed the ExportEvent object. But I don't see any way to modify the headers

**Comment by qzminski** [comment]
You have to play around with the reader and writer properties of the event: 

- https://github.com/codefog/contao-events_subscriptions/blob/1c5cb7648433baa5ef175cd5dd724bed891cda27/src/Codefog/EventsSubscriptions/Exporter.php#L115-L116
- https://github.com/codefog/contao-haste/blob/master/docs/IO/index.md

**Comment by tsarma** [comment]
Thank you very much for the Infos. It helped me to remove the unwanted columns.
