### ISSUE TITLE
Problems with reminder mails per session lately "Mails per session limit"

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#57]
Hi Kamil,

since a few days i got errors in my log and not all reminders are sent. Did anything change in the latest version?

My hosting did not change. Its an IONOS unlimited Hosting. Core newsletters or manually send event event subsribtion mails run through without problems. Even there are above 70 recipients.

Just the reminder via cron at 6 am are causing an error.

**Could not send email for message ID 17: Expected response code "250" but got code "451", with message "451-Requested action aborted 451 Mails per session limit**

Can we split this in several session or any other solution?

<img width="957" alt="Bildschirmfoto 2020-12-12 um 16 13 04" src="https://user-images.githubusercontent.com/6390770/101987636-b2a6c680-3c95-11eb-852e-928e018a083b.png">

<img width="872" alt="Bildschirmfoto 2020-12-12 um 16 15 46" src="https://user-images.githubusercontent.com/6390770/101987590-5348b680-3c95-11eb-9518-472087f0f5e6.png">

Greetings Frank

**Comment by qzminski** [comment]
Hey Frank, I suggest that you try the "queue" gateway in the Notification Center. As far as I remember it supports sending e-mails in chunks. You may need to set up a cron job for that, however.

**Comment by Kahmoon** [comment]
Thanks...i will try that. This queue mailer also triggers the event reminders?

**Comment by qzminski** [comment]
No, the events subscriptions module "tells" the notification center to send X e-mails. Then, the notification center checks what gateway it should be send with and puts e-mails in a queue, which is then executed by another cron job.

**Comment by Kahmoon** [comment]
This is due to a new global policy from IONOS

> Since December 2020, a sending limit of 20 emails per SMTP connection has been in effect for IONOS.
This limit applies to all customers and had to be introduced due to incidents in the past.
