### ISSUE TITLE
Translation issue at subscription overview

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#58]
Hi,

sinde the last updates the button is shown in englisch and also it seems to be hardcoded? I can´t find "subscriptions_overview" in any template.

<img width="502" alt="Bildschirmfoto 2021-01-02 um 15 11 43" src="https://user-images.githubusercontent.com/6390770/103459148-4277e780-4d0d-11eb-8a10-34e4224fc296.png">

The variable gets ignored
$GLOBALS['TL_LANG']['tl_calendar']['subscriptions_overview'] = ['Anmeldungsübersicht', 'Zeige eine Übersicht aller Anmeldungen für den Kalender ID %s'];

greetings

**Comment by qzminski** [comment]
Should be fixed in 2.10.5 👍🏻
