### ISSUE TITLE
You cannot create new events

### ISSUE THREAD

**Issue by do-while** [codefog/contao-events_subscriptions#6]
When creating a new event, the following error message appears:
**Warning: array_key_exists() expects parameter 2 to be array, null given in /www/htdocs/.../vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php on line 640**

If I uninstall the extension with the Contao Manager, it will work fine again. If I reinstall the extension, this error occurs again.

**My System:**
PHP Version 7.1.11-nmm1
Contao 4.4.12.0 (API-Version 0)

**Extensions (all installed via CM):**
codefog/contao-cookiebar : 1.3.3
codefog/contao-events_subscriptions : 2.0.1
codefog/contao-mobile_menu : 2.7.0
codefog/contao-news_categories : 3.0.6
delahaye/dlh_googlemaps : 2.3.2
do-while/contao-ce_be_remarks : 1.0.0
do-while/contao-backupdb-bundle : 1.2.1
erdmannfreunde/euf_overlay : 1.2.0
fritzmg/contao-backend-documentation : 1.0.3
jrgregory/m17-sticky-backend-footer : 2.0.9
madeyourday/contao-rocksolid-columns : v2.0.0
terminal42/contao-easy_themes : 2.2.6
terminal42/contao-inserttags : 1.9.4
terminal42/notification_center : 1.4.2

**Comment by qzminski** [comment]
Fixed in 2300d12.
