### ISSUE TITLE
Enhancement: Add subscribers via backend: suggest online active members

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#63]
Hi Kamil,

actually when i add subscribers via backend it also shows members which are deactivated long time ago. Its kinda risky to klick the wrong one and send a mail to an inactive student.

Members which are **not active** and **not active anymore (deactivation date)** should not be shown in this list. This would be a great enhancement for every user of this extension and probably a small change :-)

Greetings

**Comment by qzminski** [comment]
If they are no longer active, maybe they should just be deleted from the database?

**Comment by Kahmoon** [comment]
Nah, that would not be a good solution because the can be reactivated if they book other lessons. Also we use this data for history.

**Comment by qzminski** [comment]
How about this compromise? I don't want to take away a possibility of subscribing inactive members completely.

![2021-06-01 at 19 13](https://user-images.githubusercontent.com/193483/120364397-7f242b00-c30d-11eb-8a82-745c6f89f611.png)

**Comment by Kahmoon** [comment]
Hmm i´m fine with that. But does it make sense to subscribe inactive users? The only reason i see is for future events where account is not activated yet.

So let´s do it this way. Main thing is to split them to not accidently add old/inactive members.

**Comment by qzminski** [comment]
We treat a member as inactive even his account is "active", but the logging in is turned off. I can imagine a use case where somebody uses members to just manage their data without giving them option to log into the frontend. That's why I would like to keep the split into active and inactive members.

> The only reason i see is for future events where account is not activated yet.

That is also a vital reason IMO.

**Comment by Kahmoon** [comment]
Can you set active first. Actually it shows inactive first
![Bildschirmfoto 2021-06-02 um 14 48 30](https://user-images.githubusercontent.com/6390770/120482808-c82dbb00-c3b1-11eb-981d-70f64c653ea3.png)

**Comment by qzminski** [comment]
Good point, just improved that.

**Comment by Kahmoon** [comment]
Can you set the css class on inactive elemente differently then active entries?

active-result
inactive-result

This would make a css styling possible.

**Comment by qzminski** [comment]
No, as far as I know it's not possible.
