### ISSUE TITLE
Edit Event not working

### ISSUE THREAD

**Issue by wernerjoss** [codefog/contao-events_subscriptions#7]
Hello,
I have just installed events subscriptions plugin via repository, all went ok, incl. database update ok.
However, trying to set up an (existing) Calendar for use with subscriptions as described in
https://github.com/codefog/contao-events_subscriptions/blob/master/docs/02-basics.md
I do not get the expected new widgets for configuration.
see attached screenshot.
what could I try next ?
(this is a contao 3.5.31 Installation)
thanks in advance.
Werner
![sub_events](https://user-images.githubusercontent.com/36265757/35972621-e90e1e94-0cd2-11e8-8af8-99bccf519836.png)

**Comment by qzminski** [comment]
What version of the extension have you got installed? Also, what's the version of haste package (installed alongside)?

**Comment by wernerjoss** [comment]
events_subscription is 1.0.7 
what is 'haste package', is that https://github.com/codefog/contao-haste ?
(there has not been installed anything alongside events_subscrition as a dependency)

**Comment by wernerjoss** [comment]
.. I just installed mentioned haste, which also pulled NameSpaceClassloader.
but did not give other result.

**Comment by qzminski** [comment]
The 1.0.7 version is deprecated as we've got 2.0.2 at the time being. This version can be installed via composer or manually.

I update the ER description and the docs. Sorry for the confusion.

**Comment by wernerjoss** [comment]
ok, thanks, 2.0.2 does work as described :)
I just add a zip file with some updated german translations.
[de.zip](https://github.com/codefog/contao-events_subscriptions/files/1714383/de.zip)

**Comment by qzminski** [comment]
Thanks, I have just released a 2.0.4 with updated translations :wink:
