### ISSUE TITLE
Variables in notifications create errors

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#71]
Hi Kamil,

actually i cannot safe existing notifications. I get errors on variables with "if query"

`{if event_startTime!=""}Uhrzeit: ##event_startTime##{endif}{if event_endTime!=""} - ##event_endTime## Uhr{endif}`
"Unexpected character "#" around position 17 for expression `event_startTime!=""`."

Also other variables from event don´t work anymore. But the existing mails a working correctly.

`{if subscription_username!=""}`
Unexpected character "#" around position 23 for expression `subscription_username!=""`.

Contao: 4.11.9
NC: 1.5.18
Event Subscriptions: 2.12.13

If this is an NC thing: https://github.com/terminal42/contao-notification_center/issues/239

**Comment by qzminski** [comment]
See discussion in terminal42/contao-notification_center/issues/239.
