### ISSUE TITLE
Export subscriber file names year-month-day

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#77]
Hi Kamil,

actually i have to export lots of events to import them in Excel. Actually the filenames are a problem in finder sorting because the date is in wrong direction.

<img width="221" alt="Bildschirmfoto 2021-12-07 um 17 38 19" src="https://user-images.githubusercontent.com/6390770/145069506-eec2ca9f-4f52-4125-9782-010459eae2b0.png">

As you can see the sortings comes from day which causes a totaly mixed up sorting - july, december, august, june ;-).

It would be way better if it was year-month-day (event-xyz-2021-12-04.xls) insted of day-month-year (event-xyz-04-12-2021.xls)

I think this would be a very usefull small tweak.

Greetings

**Comment by Aybee** [comment]
Erinnert mich an die Postbank. Da werden die Kontoauszüge auch mit verdrehtem Datum erzeugt. Auf meine Anfrage mit Begründung dies zu ändern wurde nichts unternommen.

Meanwhile you can try the freeware Advanced Renamer https://www.advancedrenamer.com/. You can change the filenames with regex. Save your code in a file in the same folder so you can easily start the renamer with double click.

**Comment by Kahmoon** [comment]
Thanks...i´m on Mac. Advanced Renamer is for Windows only.

Fixing export names would be a much better solution then creating additional work, renaming files afterwards.

**Comment by qzminski** [comment]
The date format is coming from your Contao system settings. You can change it there, but it will also affect the whole backend.

**Comment by Kahmoon** [comment]
Hmm thats bad...any workaround to change just on export?

**Comment by qzminski** [comment]
I have just changed it, please update the extension.

**Comment by Kahmoon** [comment]
Great!

**Comment by Aybee** [comment]
> Fixing export names would be a much better solution then creating additional work, renaming files afterwards.

Yes, thats why I wrote meanwhile 😉
