### ISSUE TITLE
Waiting list mail is not sent

### ISSUE THREAD

**Issue by eiswurm** [codefog/contao-events_subscriptions#78]
If only one participant is on the waiting list and this person slips onto the normal participant list, the waiting list email will not be sent. If more than one participant is on the waiting list and one of them slips onto the participant list, the email will be sent.
In our opinion it could be a bug in the NotificationListener :: getWaitingListPromotedSubscription ()

**Comment by eiswurm** [comment]
We have been able to narrow the bug regarding the sending of the mail "Change of waiting list". The bug appeared on other setups and customers as well. But the error occurs just from version 2.13. Till 2.12 everything is fine. The mail is sent.

Again: If you delete the participant who was the first to register for an event and a waiting list participant slips onto the participant list, the mail "Change of waiting list" is not sent. If you delete the second, third or nth participant, the mail will be sent. The same error occurs if you remove more than one participant from the list of participants.

**Comment by qzminski** [comment]
Would you be able to patch your system with https://github.com/codefog/contao-events_subscriptions/commit/9c18585db39ff97583849369274c5d30c3c9a716 commit and see if it fixes the issue?

**Comment by eiswurm** [comment]
Yes, this fixes the issue.

**Comment by qzminski** [comment]
Perfect, I have just released version 2.14.2.

**Comment by Kahmoon** [comment]
Is there maybe a new bug? Actually 1 student canceled his subscription (Daniel). There were two students on the waiting list (Alexandra #1, Thomas #2). The first one was promoted. The second one also got the "promoted mail" but instantly gets unsubscribed from this eventafterwards.

The first unsuscribe and promote from waiting list of this event has 1 hour difference!?

![SCR-20220222-eag](https://user-images.githubusercontent.com/6390770/155101155-427e95d2-3e1c-4f3c-97f5-37881f34a2a4.png)
