### ISSUE TITLE
Enable subscriptions section not visible

### ISSUE THREAD

**Issue by renkens** [codefog/contao-events_subscriptions#8]
Contao 3.5.x

After installing event_subsccriptions (and haste and notification_centre), I don't see the 

Enable the subscriptions section as described in 

https://github.com/codefog/contao-events_subscriptions/blob/master/docs/02-basics.md

What can I do? Any furthert information required?

**Comment by qzminski** [comment]
How did you actually install it? What version of the module have you installed exactly?

**Comment by renkens** [comment]
Good morning,

 


I installed version  1.0.7

 

through the Contao Extension Manager, can’t use  the Repository Manger due to limitations of my web hoster.

 

What I found: the Subscription Settings are displayed

 

Would it help to install it manually? How? 

 

 

Thanks for helping me.

 

Kind Regards

 

Willi Renkens

 

 

 

Von: Kamil Kuzminski [mailto:notifications@github.com] 
Gesendet: Montag, 16. April 2018 20:38
An: codefog/contao-events_subscriptions
Cc: renkens; Author
Betreff: Re: [codefog/contao-events_subscriptions] Enable subscriptions section not visible (#8)

 

How did you actually install it? What version of the module have you installed exactly?

**Comment by qzminski** [comment]
I'm sorry but the 1.x version is no longer supported. Please use 2.0 instead.

**Comment by renkens** [comment]
Sorry to bother you again,

 

I have now manually installed version 2 and it looks good so far. Is there a detailed description available on how to insert on of the front end modules into a given or new event? I am stuck.

 

Kind Regards

 

Willi Renkens

 

Von: Kamil Kuzminski [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. April 2018 09:16
An: codefog/contao-events_subscriptions
Cc: renkens; Author
Betreff: Re: [codefog/contao-events_subscriptions] Enable subscriptions section not visible (#8)

 

I'm sorry but the 1.x version is no longer supported. Please use 2.0 instead.

**Comment by qzminski** [comment]
The documentation is in the README file: https://github.com/codefog/contao-events_subscriptions/#documentation <https://github.com/codefog/contao-events_subscriptions/#documentation>
--
Kamil Kuzminski
Codefog - https://codefog.pl

**Comment by renkens** [comment]
I found that, but I don‘t find:

 

Event list subscribe

Based on the genuine event list module enhanced with the subscription functionality. Since it is based on the genuine event list module it offers the same features as it's ancestor.

Event reader subscribe

Based on the genuine event reader module enhanced with the subscription functionality. Since it is based on the genuine event reader module it offers the same features as it's ancestor.

Subscribe event form

The module that should be placed on the same page as the event reader module. It displays a subscription form for the current event.

User event subscriptions

Etc.

 

Kind regards

 

Willi Renkens

 

 

 

 

Von: Kamil Kuzminski [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. April 2018 15:46
An: codefog/contao-events_subscriptions
Cc: renkens; Author
Betreff: Re: [codefog/contao-events_subscriptions] Enable subscriptions section not visible (#8)

 

The documentation is in the README file: https://github.com/codefog/contao-events_subscriptions/#documentation <https://github.com/codefog/contao-events_subscriptions/#documentation>
--
Kamil Kuzminski
Codefog - https://codefog.pl

**Comment by renkens** [comment]
Hello Kamil,

 

I could successfully generate a subscription form and subscribe participants.

 

Sorry, but all the efforts and documents lead to: Asking you for a quotation for:

 

Subscribe for a certain event until a certain date and time

Display all subscribed users for a certain event (as a module)

From this list, unsubscribe until a certain date and time (for logged in users)

 

 

Could you give me a quotation for this, please.

 

Thanks

 

 

 

Von: Kamil Kuzminski [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. April 2018 15:46
An: codefog/contao-events_subscriptions
Cc: renkens; Author
Betreff: Re: [codefog/contao-events_subscriptions] Enable subscriptions section not visible (#8)

 

The documentation is in the README file: https://github.com/codefog/contao-events_subscriptions/#documentation <https://github.com/codefog/contao-events_subscriptions/#documentation>
--
Kamil Kuzminski
Codefog - https://codefog.pl
