### ISSUE TITLE
Webside throwing error "event ID ... not exist"

### ISSUE THREAD

**Issue by Ernestopheles** [codefog/contao-events_subscriptions#86]
Calling the homepage I get this error since 1 day:
[2022-08-21T19:22:30.161931+02:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The event ID "802" does not exist" at .../contao/vendor/codefog/contao-events_subscriptions/src/Codefog/EventsSubscriptions/EventConfig.php line 245 {"exception":"[object] (InvalidArgumentException(code: 0): The event ID \"802\" does not exist at .../contao/vendor/codefog/contao-events_subscriptions/src/Codefog/EventsSubscriptions/EventConfig.php:245)"} []
After refreshing the browser window the homepage is shown correctly.

This repeating error includes an increasing event ID (ID will be inceased by 3 each time). These ervent IDs do not exist in the database.

What I changed: Update to Contao 4.13.8 and moved some events to a different calendar

**Comment by qzminski** [comment]
Do you use any custom templates in your Contao setup?

**Comment by Ernestopheles** [comment]
Mate theme

**Comment by Ernestopheles** [comment]
Thanky for your hint; clicking on "synchronize theme files" in my backend solved the issue.

**Comment by Ernestopheles** [comment]
Too early being closed, error still existing...

**Comment by Ernestopheles** [comment]
leaving ical Import unchecked prevents the error, so solution will possibly ly somewhere with ical import

**Comment by qzminski** [comment]
This error is likely specific to your setup, 3rd party extensions and/or your custom code.

**Comment by Ernestopheles** [comment]
Well, I said what I changed , above. So I would exclude setup, 3rd party extensions and custom code.
The event ID is increased by 3 and there are 3 events being imported - maybe this gives a hint?

**Comment by Ernestopheles** [comment]
Not happy you closed this

**Comment by qzminski** [comment]
There is no ical import feature in the extension… or am I missing something?

**Comment by Kahmoon** [comment]
There is no iCal feature at all in this extension!? I´m using iCal but from another extension (oneup/contao-ical-export) and its fine.

**Comment by Ernestopheles** [comment]
see error message, please:  contao-events_subscriptions
I am using contao-ical-php8-bundle as well

**Comment by Kahmoon** [comment]
Then maybe this causes the error. Im using event_subscriptions + oneup/contao-ical-export and its fine.

But there is no ical import feature from contao-event-subscriptions

**Comment by Ernestopheles** [comment]
Yes, thats my thinking as well, did have other problems caused by them I will try what you said, thanks a lot.

**Comment by Ernestopheles** [comment]
Habe oneup/contao-ical-export installiert, aber das funktioniert scheinbar noch nicht, da die DB-Änderung scheinbar nicht durchgeführt wird, da die Drops aus der Deinstallation der anderen extension zuerst abgearbeitet werden müssten, vermutlich.
Ausserdem brauche ich auch einen ical import.

**Comment by Kahmoon** [comment]
Then you have to open an issue an contao-php8-ical-bundle

**Comment by Ernestopheles** [comment]
> Then you have to open an issue an contao-php8-ical-bundle (https://github.com/Craffft/contao-calendar-ical-bundle/issues)
This is unfortunately not possible...

> It would be helpfull if you reproduce this error in debug mode to get the stack trace error .
You are right, sorry, I decided to leave the ical extension behind, too late...
