### ISSUE TITLE
New option "send notification" manually is ignoring member data?

### ISSUE THREAD

**Issue by Kahmoon** [codefog/contao-events_subscriptions#88]
Hi Kamil,

i tried the new option so send notifications manually to all subscribers for the first time. Here i copied another notification (event-subscribe) which uses the variables ##member_firstname## without problems.

For example unsubscription:

![SCR-20220913-dru](https://user-images.githubusercontent.com/6390770/189844028-65bfd449-07ef-40f6-abe8-6627fd17a2f1.png)

 
When i use the manual send option "event notification", this variable is **not filled** with memberdata.

![SCR-20220913-dq6](https://user-images.githubusercontent.com/6390770/189843940-644694e2-ba90-46ed-aeb7-109e0a55c0ec.png)

![SCR-20220913-dsw](https://user-images.githubusercontent.com/6390770/189844223-ad8cf34e-ea72-4f13-98d2-fe2533f853cd.png)

Anything i did wrong here or is it a bug?

greetings
Frank

**Comment by qzminski** [comment]
Just to be sure: the recipient of this notification is a member?

**Comment by qzminski** [comment]
Moreover, are you sure the member still exists?

**Comment by Kahmoon** [comment]
Yes, all of the receipients are active members. They all got ##member_firstname##

**Comment by qzminski** [comment]
Please use the `subscription_*` tokens there, as it sends a notification to the existing subscribers (which can be both guest and members).

**Comment by Kahmoon** [comment]
Oh damn....i´m stupid! Sorry! I was to focues on notification center variables. ##subscription_firstname## is working fine.
