### ISSUE TITLE
Module User event subscriptions: getSchemaOrgData is not set or not a callable

### ISSUE THREAD

**Issue by rustykowski** [codefog/contao-events_subscriptions#93]
PHP 8.1
Contao 4.13
contao-events_subscriptions: 2.13.* – 2.16.*

When I use the mentioned module, I get a critical error if the logged in user has subscribed to an event.

var/logs:
```
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "getSchemaOrgData is not set or not a callable" at /.../vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php line 174
```

Additionally, I have a warning in debug mode regardless of whether I am subscribed to an event:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1775048/204336948-888e9840-a0b2-4c16-a05b-e4cfca2cf51b.png">

**Comment by rustykowski** [comment]
The issue is new since I upgraded from PHP 7.4 and Contao 4.9.

**Comment by qzminski** [comment]
Please update to 2.16.3 and it should fix the main problem. The PHP warnings on the screenshot may happen though, as I didn't have time yet to check all the warnings.

**Comment by rustykowski** [comment]
The problem is solved. Crazy how fast you fixed it! Thanks a lot!
